### ISSUE TITLE
-XReplacePrimitives breakes -XhashCode and -Xequals

### ISSUE THREAD

**Issue by jenspopp** [krasa/krasa-jaxb-tools#34]
If the Arguments 
<arg>-XhashCode</arg> or
<arg>-Xequals</arg>

and
<arg>-XReplacePrimitives</arg>

are used together, the code doesn't work anymore if any primitives are replaced. The generated hashcode and equals methods use still the primitive and assign the Object to the primitive, e.g.

 long theDivisionId;
 theDivisionId = this.getDivisionId();

if the method this.getDivisionId() returns null (because it is a Long Object not initialized) the code throws a NullPointerException.

**Comment by krasa** [comment]
works for me. could you provide more details or make a quickstart? 
preferably in https://github.com/krasa/krasa-jaxb-tools-example

**Comment by jenspopp** [comment]
Hi,



I attached an example generated file, once with and once without the Flag
XReplacePrimitives. If you look at lines 168/169 in hashCode and 210/211 in
equals you have e.g. the lines:



            *long* lhsDivisionId;

            lhsDivisionId = *this*.getDivisionId();





the second line is no problem as long as getDivisionId() returns a not null
value. If it is a primitive (long), this is a given, if it is type Long it
can be null (e.g. if divisionId is uninitialized). If the code is called
(e.g. for a Set-insert operation) this causes a NullPointerException
because null is assigned to a primitive. So basically XReplacePrimitives
should also replace the primitives in hashCode and equals to avoid that
scenario or it should give a warning, that something like this can happen
if used with the options -XhashCode or -Xequals...



Best Regards



Jens



*Von:* Vojtěch Krása [mailto:notifications@github.com]
*Gesendet:* Donnerstag, 12. März 2015 00:47
*An:* krasa/krasa-jaxb-tools
*Cc**:* jenspopp
*Betreff:* Re: [krasa-jaxb-tools] -XReplacePrimitives breakes -XhashCode
and -Xequals (#34)



works for me. could you provide more details or make a quickstart?
preferably in https://github.com/krasa/krasa-jaxb-tools-example

—
Reply to this email directly or view it on GitHub
<https://github.com/krasa/krasa-jaxb-tools/issues/34#issuecomment-78397701>.

-- 
camLine GmbH
85238 Petershausen, Industriering 4a, Deutschland
Amtsgericht München HRB 88821
Geschäftsführer: Heinz Linsmaier (CEO), Bernhard Jofer, Georg Ruetz

**Comment by krasa** [comment]
I see, that is so strange, it works for me totally fine in other project. :(

**Comment by jenspopp** [comment]
As mentioned, it works perfectly fine, if all values are initialized. The problem appears only, if a replaced type (that was a primitive before) is uninitialized (null) AND you call the hashCode or equals method on a generated object with uninitialized values (e.g. by placing it in a Set or Map).

**Comment by krasa** [comment]
Ok, I know why is that, the problem is in finding getters/setters for the field. Xjc sometimes names them differently, so the plugin is unable to find them.

**Comment by krasa** [comment]
fixed and released.
