### ISSUE TITLE
xs:enumeration is not translated correctly to annotations

### ISSUE THREAD

**Issue by asakelliou** [krasa/krasa-jaxb-tools#41]
Give the following piece of an xsd :

            <xsd:enumeration value="12" />
            <xsd:enumeration value="13" />
            <xsd:enumeration value="14" />
            <xsd:enumeration value="15" />
            <xsd:enumeration value="19" />
            <xsd:enumeration value="26" />
            <xsd:enumeration value="35" />
            <xsd:enumeration value="37" />
            <xsd:enumeration value="38" />
            <xsd:enumeration value="39" />
            <xsd:enumeration value="40" />
            <xsd:enumeration value="90" />
            <xsd:enumeration value="91" />
            <xsd:enumeration value="92" />
            <xsd:enumeration value="93" />

the translated annotations are :

 @Pattern.List({
        @Pattern(regexp = "12"),
        @Pattern(regexp = "13"),
        @Pattern(regexp = "14"),
        @Pattern(regexp = "15"),
        @Pattern(regexp = "19"),
        @Pattern(regexp = "26"),
        @Pattern(regexp = "35"),
        @Pattern(regexp = "37"),
        @Pattern(regexp = "38"),
        @Pattern(regexp = "39"),
        @Pattern(regexp = "40"),
        @Pattern(regexp = "90"),
        @Pattern(regexp = "91"),
        @Pattern(regexp = "92"),
        @Pattern(regexp = "93")
    })

Which of course is wrong because the given value must satisfy all the patterns in the list at the same time.

**Comment by ST-DDT** [comment]
@asakelliou Are you sure?
AFAIK this must only fullfill one instead of all.
Do you have some official documentation that supports your theses.
I didn't found anything on this topic though.

**Comment by asakelliou** [comment]
When I had this code (I have transformed the field to enumeration througf jaxb.xjb), when it was validated against a single value (ie "93"), I got 14 validation errors that informed me of wrong pattern, each with the pattern from the list. If you really need the error messages, let me know and I will try re recreate them sometime in the future.

**Comment by StefanS** [comment]
Hi, 
this issue affects me too.

Given xsd part : 
```
<element name="sex" minOccurs="0">
      <simpleType>
           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
                <enumeration value="f"/>
                <enumeration value="m"/>
            </restriction>
      </simpleType>
</element>
```

generated java class part:
```
 @Pattern.List({
       @Pattern(regexp = "f"),
       @Pattern(regexp = "m")
 })
 protected String sex;
```

xml with: 
`<sex>m</sex>`
leads to message:
'muss auf Ausdruck "f" passen'  (german for must match expression 'f')

xml with:
`<sex>f</sex>`
leads to message:
'muss auf Ausdruck "m" passen'  (german for must match expression 'm')

For the validation I used 'org.hibernate:hibernate-validator:5.2.2.Final'

**Comment by mschaefers** [comment]
This problem affects me as well. I strongly suggest to create a pull request for this, @StefanS

**Comment by martinsznapka** [comment]
I have exactly same issue. Pattern.List constraint is evaluated as AND for each Pattern, so validating enumeration always fail.

@krasa Can you please accept merge request from @StefanS 
Díky ;)

**Comment by krasa** [comment]
I am currently on remote location without my dev PC, so I cannot test it and release it, but I will be back in a week or so.. :-)

**Comment by martinsznapka** [comment]
Ok, np, thx.
BTW the patch works correctly. It generates:
`@Pattern(regexp = "(enumvalue1)|(enumvalue2)|(enumvalue3)")`

**Comment by krasa** [comment]
1.5 released.
