### ISSUE TITLE
Exception thrown if XSD union is used

### ISSUE THREAD

**Issue by cipriandobra** [krasa/krasa-jaxb-tools#42]
For the next situation:

``` xml
<xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        targetNamespace="c" xmlns:c="c"
        elementFormDefault="qualified">

    <xsd:simpleType name="DateOrDateTimeType">
        <xsd:union memberTypes="xsd:date xsd:dateTime"/>
    </xsd:simpleType>

    <xsd:complexType name="TimeInstantType">
        <xsd:simpleContent>
            <xsd:extension base="c:DateOrDateTimeType">
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>
```

the plugin throws the exception:
<code>Attribute value added to class TimeInstantType
java.lang.ClassCastException: com.sun.xml.xsom.impl.UnionSimpleTypeImpl cannot be cast to com.sun.xml.xsom.impl.RestrictionSimpleTypeImpl
    at com.sun.tools.xjc.addon.krasa.JaxbValidationsPlugins.processAttribute(JaxbValidationsPlugins.java:416)
</code>

When this happens the processing of the rest of the schema(s) does not continue.

**Comment by mandyWW** [comment]
Any update on this? I am having the same issue.

**Comment by cipriandobra** [comment]
I have added at the beginning of the function processAttribute:
```
XSComponent definition = property.getSchemaComponent();
		
if ( false == definition instanceof RestrictionSimpleTypeImpl ) {
	return; // this causes a crash below
}
```
and removed the existing line `XSComponent definition = property.getSchemaComponent();` in the same function.

**Comment by krasa** [comment]
Thanks!
