### ISSUE TITLE
Bug in @Digits annotations

### ISSUE THREAD

**Issue by NBau** [krasa/krasa-jaxb-tools#58]
It seems that xml schema and jsr303 have a different style of expressing the allowed digits. In xml schema, you provide `totaldigits` and `fractionDigits`, in jsr303 it is `integer` and `fraction`. The plugin assumes that `totalDigits` equals `integer`, but correctly it should be `integer = totalDigits - fractionDigits`.

**Comment by krasa** [comment]
Please read https://github.com/krasa/krasa-jaxb-tools/issues/40
