### ISSUE TITLE
Enumeration pattern is not escaped

### ISSUE THREAD

**Issue by ninckblokje** [krasa/krasa-jaxb-tools#69]
Hi,

When krasa-jaxb-tools generate the @Package annotation, then the pattern is not escaped. The pattern is taken form the value attribute of the enumeration element. This element is a literal string (if I am correct). So placing a parentheses will result in a regular expression instead of a literal pattern.

Example:

`<xs:simpleType>
  <xs:restriction base="xs:string">
    <xs:enumeration value="test 123"/>
    <xs:enumeration value="test (123)"/>
  </xs:restriction>
</xs:simpleType>
`

This will result in the following annotation:
`@Pattern(regexp = "(test 123)|(test (123))")`

`test (123)` is now a regular expression, because the parentheses are not escaped.

Would you be willing to consider a pull request for this?

**Comment by krasa** [comment]
Reverting for now.

I tried it and it produces
```
	@Pattern.List({ @Pattern(regexp = "[A-Z]"), @Pattern(regexp = "(\\Q[0-9]\\E)|(\\Q[A-B]\\E)") })
	protected String multiplePatternsWithBase;
```
for
```

	<xsd:complexType name="PatternElement">
		<xsd:sequence>
			<xsd:element maxOccurs="1" minOccurs="0" name="multiplePatternsWithBase" type="a:patternList"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="patternList">
		<xsd:restriction base="a:patternListBase">
			<xsd:pattern value="[0-9]"/>
			<xsd:pattern value="[A-B]"/>
		</xsd:restriction>
	</xsd:simpleType>
```

You can try that in https://github.com/krasa/krasa-jaxb-tools-example

**Comment by krasa** [comment]
Actually, it just needed a little fix. Thanks!
